(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.Select = factory());
}(this, (function () { 'use strict';

	function noop() {}

	function assign(tar, src) {
		for (var k in src) tar[k] = src[k];
		return tar;
	}

	function assignTrue(tar, src) {
		for (var k in src) tar[k] = 1;
		return tar;
	}

	function append(target, node) {
		target.appendChild(node);
	}

	function insert(target, node, anchor) {
		target.insertBefore(node, anchor);
	}

	function detachNode(node) {
		node.parentNode.removeChild(node);
	}

	function createElement(name) {
		return document.createElement(name);
	}

	function blankObject() {
		return Object.create(null);
	}

	function destroy(detach) {
		this.destroy = noop;
		this.fire('destroy');
		this.set = noop;

		this._fragment.d(detach !== false);
		this._fragment = null;
		this._state = {};
	}

	function _differs(a, b) {
		return a != a ? b == b : a !== b || ((a && typeof a === 'object') || typeof a === 'function');
	}

	function fire(eventName, data) {
		var handlers =
			eventName in this._handlers && this._handlers[eventName].slice();
		if (!handlers) return;

		for (var i = 0; i < handlers.length; i += 1) {
			var handler = handlers[i];

			if (!handler.__calling) {
				try {
					handler.__calling = true;
					handler.call(this, data);
				} finally {
					handler.__calling = false;
				}
			}
		}
	}

	function flush(component) {
		component._lock = true;
		callAll(component._beforecreate);
		callAll(component._oncreate);
		callAll(component._aftercreate);
		component._lock = false;
	}

	function get() {
		return this._state;
	}

	function init(component, options) {
		component._handlers = blankObject();
		component._slots = blankObject();
		component._bind = options._bind;
		component._staged = {};

		component.options = options;
		component.root = options.root || component;
		component.store = options.store || component.root.store;

		if (!options.root) {
			component._beforecreate = [];
			component._oncreate = [];
			component._aftercreate = [];
		}
	}

	function on(eventName, handler) {
		var handlers = this._handlers[eventName] || (this._handlers[eventName] = []);
		handlers.push(handler);

		return {
			cancel: function() {
				var index = handlers.indexOf(handler);
				if (~index) handlers.splice(index, 1);
			}
		};
	}

	function set(newState) {
		this._set(assign({}, newState));
		if (this.root._lock) return;
		flush(this.root);
	}

	function _set(newState) {
		var oldState = this._state,
			changed = {},
			dirty = false;

		newState = assign(this._staged, newState);
		this._staged = {};

		for (var key in newState) {
			if (this._differs(newState[key], oldState[key])) changed[key] = dirty = true;
		}
		if (!dirty) return;

		this._state = assign(assign({}, oldState), newState);
		this._recompute(changed, this._state);
		if (this._bind) this._bind(changed, this._state);

		if (this._fragment) {
			this.fire("state", { changed: changed, current: this._state, previous: oldState });
			this._fragment.p(changed, this._state);
			this.fire("update", { changed: changed, current: this._state, previous: oldState });
		}
	}

	function _stage(newState) {
		assign(this._staged, newState);
	}

	function callAll(fns) {
		while (fns && fns.length) fns.shift()();
	}

	function _mount(target, anchor) {
		this._fragment[this._fragment.i ? 'i' : 'm'](target, anchor || null);
	}

	var proto = {
		destroy,
		get,
		fire,
		on,
		set,
		_recompute: noop,
		_set,
		_stage,
		_mount,
		_differs
	};

	/* src/Select.html generated by Svelte v2.15.3 */

	function onstate({changed, current, previous}) {
	  if (!previous) return;

	  if (changed.isFocused) {
	    const {isFocused} = current;
	    if (isFocused) {
	      this.refs.input.focus();
	    }
	  }
	}
	function add_css() {
		var style = createElement("style");
		style.id = 'svelte-6lye1b-style';
		style.textContent = ".container.svelte-6lye1b{border:1px solid #D8DBDF;border-radius:3px;height:44px}.container.svelte-6lye1b input.svelte-6lye1b{border:none;color:#3F4F5F;height:44px;line-height:44px;padding:0 16px;width:100%;background:transparent;font-size:14px;letter-spacing:-0.08px}.container.svelte-6lye1b input.svelte-6lye1b::placeholder{color:#78848F}.container.svelte-6lye1b input.svelte-6lye1b:focus{outline:none}.container.svelte-6lye1b:hover{border-color:#b2b8bf}.container.focused.svelte-6lye1b{border-color:#006FE8}";
		append(document.head, style);
	}

	function create_main_fragment(component, ctx) {
		var div, input, div_class_value;

		return {
			c() {
				div = createElement("div");
				input = createElement("input");
				input.placeholder = "Placeholder text";
				input.className = "svelte-6lye1b";
				div.className = div_class_value = "container " + (ctx.isFocused ? 'focused' : '') + " svelte-6lye1b";
			},

			m(target, anchor) {
				insert(target, div, anchor);
				append(div, input);
				component.refs.input = input;
			},

			p(changed, ctx) {
				if ((changed.isFocused) && div_class_value !== (div_class_value = "container " + (ctx.isFocused ? 'focused' : '') + " svelte-6lye1b")) {
					div.className = div_class_value;
				}
			},

			d(detach) {
				if (detach) {
					detachNode(div);
				}

				if (component.refs.input === input) component.refs.input = null;
			}
		};
	}

	function Select(options) {
		init(this, options);
		this.refs = {};
		this._state = assign({}, options.data);
		this._intro = true;

		this._handlers.state = [onstate];

		if (!document.getElementById("svelte-6lye1b-style")) add_css();

		onstate.call(this, { changed: assignTrue({}, this._state), current: this._state });

		this._fragment = create_main_fragment(this, this._state);

		this.root._oncreate.push(() => {
			this.fire("update", { changed: assignTrue({}, this._state), current: this._state });
		});

		if (options.target) {
			this._fragment.c();
			this._mount(options.target, options.anchor);

			flush(this);
		}
	}

	assign(Select.prototype, proto);

	return Select;

})));
